### ISSUE TITLE
0.0.1 MVP TODO list

### ISSUE THREAD

**Issue by GrawrGG** [GrawrGG/HistoryBooks#1]
# History Books 0.0.1
Features include:
- list of recently run **dungeons** only
- dungeon detail including success/fail, dungeon name, duration, keystone level, players, specs

## Tracking
- [ ] Use milliseconds for time
- [ ] Store currently-in-progress activities in character SavedVariables
- [ ] Handle resuming activities after disconnect
- [ ] Build a Player DB for future filtering

## UI
- [ ] List/Detail pattern
- [ ] Split list by time period

##  Meta work
- [ ] Figure out packaging/publishing (particularly for addon managers that can download addons directly from Github)
- [ ] Styleguide + linter
